export const ADD_QUESTION = "ADD_QUESTION";
export const REMOVE_QUESTION = "REMOVE_QUESTION";
export const GET_QUESTIONS = "REMOVE_QUESTIONS";
export const GET_QUESTIONS_BY_USERID = "GET_QUESTIONS_BY_USERID";